import "@/styles/globals.css";
import "material-icons/iconfont/material-icons.css";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import Header from "@/components/UI/commons/header";
import { UIProvider } from "@/app/nextUIprovider";
import { ShopifyUIProvider } from "@/app/shopifyUIProvider";

export const metadata: Metadata = {
  title: "Shopify Store with NextJS",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["100", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`light ${roboto.className}`}>
      <body>
        <UIProvider>
          <ShopifyUIProvider>
            <Header />
            <main className="m-auto">{children}</main>
          </ShopifyUIProvider>
        </UIProvider>
      </body>
    </html>
  );
}
