
import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Provider } from './nextUIprovider';

export const metadata: Metadata = {
  title: 'Shopify Store with NextJS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
